package com.stcodesapp.noteit.constants;

public class Constants {
    public static String[] FULL_MONTHS = {"January","February","March","April","May","June","July","August","September","October","November","December"};
    public static String[] DAYS_OF_WEEK = {"Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"};
    public static String[] AM_PM = {"AM","PM"};

    public static final String EMPTY_STRING = "";
    public static final String OPEN = "Open?";
    public static final int WITH_KEYBOARD_MAX_LINE= 6;
    public static final int FULL_SCREEN_MAX_LINE= 20;
    public static final int MEGABYTE_DIVISOR= 1048576;
    public static final String MEGABYTE= "MB";
    public static final String OPEN_AUDIO_FILE_TYPE= "audio/*";
    public static final String TETX2SPEECH_DATABASE = "text22speech_database";
    public static final String API_KEY = "8d753ea99f332e99c7f50794b76bfce01910647f";
    public static final String ANDROID = "Android";
    public static final String LANGUAGE_FILE = "languages.json";
    public static final String CREDENTIAL_FILE = "api_credentials.json";
    public static final String LANGUAGE_TITLE = "title";
    public static final String LANGUAGE_CODE = "code";
    public static final String JSON_ENCODER = "UTF-8";
    public static final String FILE_DIRECTORY = "Text2Speech/";
    public static final String MP3_FILE_EXT = ".mp3";
    public static final String DEFAULT_LANGUAGE_MODEL = "dlm";
    public static final String DEFAULT_LANGUAGE_1_TITLE = "dl1t";
    public static final String DEFAULT_LANGUAGE_2_TITLE = "dl2t";
    public static final String DEFAULT_LANGUAGE_1_CODE = "dl1c";
    public static final String DEFAULT_LANGUAGE_2_CODE = "dl2c";
    public static final String PLAYSTORE_BASE_URL = "https://play.google.com/store/apps/details?id=";
    public static final String INVERSE_AI_URL = "https://www.inverseai.com/";
    public static final String TEXT_TYPE = "text/plain";
    public static final String SHARE_SUBJECT = "Subject Here";
    public static final String SHARE_VIA= "Subject Via";
    public static final String SHARE_BODY= "Check The Awesome Language Translation Application for Free. Get it from ";
    public static final String TRANSLATOR = "com.inverseai.language_translator_voice_text";
    public static final String NOISE_REDUCER = "com.inverseai.noice_reducer";
    public static final String AVM = "com.inverseai.audio_video_manager";
    public static final String OCR = "com.inverseai.image_to_text_OCR_scanner";
    public static final String BG_CHANGER = "com.inverseai.auto_blur_background_changer";
    public static final String TEXT_2_SPEECH = "com.inverseai.text2speech";
    public static final String EMAIL_SUBJECT= "Email Support For ";
    public static final String INVERSE_AI_MAIL= "inverseaibd@gmail.com";
    public static final String EMAIL_ADDRESS= "mailto:"+INVERSE_AI_MAIL;
    public static final String ENGLISH = "English";
    public static final String EN = "en";
    public static final String CHINESE = "Chinese";
    public static final String CN = "cn";
    public static final String BENGALI = "Bengali";
    public static final String SLASH = "/";
    public static final String BN = "bn";
    public static final String DOTS = "...";
    public static final int MAX_HISTORY_TEXT_LENGTH = 40;
    public static final int MAX_LANGUAGE_NAME_LENGTH = 8;
    public static final int FULL = 100;
    public static final int HALF = 50;
    public static final int QUARTER = 25;
    public static final int NOT_FOUND = -1;
    public static final int ZERO = 0;
    public static final int MAX_RECENT_TRANSLATION = 5;
    public static final long ONE_HUNDRED = 100;
    public static final int INITIAL_PITCH = 50;
    public static final int DEFAULT_SPEED = 1;
    public static final int DEFAULT_VOLUME = 50;
    public static final int DEFAULT_PITCH = 1;
    public static boolean IS_SUBSCRIBED_USER = false;
    public static final String ZERO_SLASH = "0/";
    public static final String BASE_64_ENCODED_PUBLIC_KEY ="MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA9hIFhQwVFWsNchKZyN9hgqN7hkHoLsD22WG9ZLWu2QAhI/srqMCcDwfo8FkFv/g6/gZh3TsrB/vSsSa9vzfgHaYcVmreCUhjt/lcRyrnv0k8i9zRwaEWCDj1YvTvNLm7o+vf3tkBpLYhEybsmnANxwSXH0sBsrsDX6xs6RbyZ2PjFkk6cfEkpMaEdFr2gwBM7gorPmKLjg88ot7W5akxm8/huyB0hTP5kYjtQIf72q16V935mI7qv4DL7rEShQJQK71pwTGthJAyFKqc9+GFdzlkKjXmUYPFV9fER472bh7J+TsDohbyZjCiJ7DVhiBZxvuzxwoH2T9QuYWhgXCMhwIDAQAB";
    public static final int UNKNOWN_TEXT=-1;
    public static final int ORIGINAL_TEXT=1;
    public static final int TRANSLATED_TEXT=2;
    public static final int TRANSLATION_PURPOSE = 1;
    public static final int CHARACTER_SHOWING_PURPOSE = 2;
    public static final int CHARACTER_SHOW_FROM_CACHE_PURPOSE = 3;
    public static final String DEFAULT_TRANSLATION="Default Translation (";
    public static final String TO =" to ";
    public static final String CLOSE_BRACKET =")";
    public static final String space = " ";
    public static final String DASH = "-";
    public static final String UNDERSCORE = "_";

}

